### ISSUE TITLE
Getting error: unknown file type '.pyx' when installing from source

### ISSUE THREAD

**Issue by cianwilson** [drufat/triangle#13]
I'm trying to build on a cluster where I'm having to manually install everything from source.  When I run:
`python setup.py install --prefix=...`
I get the error:
```
building 'triangle.core' extension
error: unknown file type '.pyx' (from 'triangle/core.pyx')
```

I'm using:
- python version 2.7.2
- numpy version 1.6.2
- setuptools version 18.4
- cython version 0.24.1

Using the first answer [here](http://stackoverflow.com/questions/32528560/using-setuptools-to-create-a-cython-package-calling-an-external-c-library) I modified `setup.py` with the [attached patch](https://github.com/drufat/triangle/files/374096/triangle-cythonize.txt) and it worked.  I'm not familiar with python setup so can't comment on why this is necessary on this cluster (but isn't necessary on my local machine) but wanted to flag it in case it's useful to anyone else.

**Comment by drufat** [comment]
Try upgrading setuptools. I am using version 23.1.0

**Comment by LonelyDeer** [comment]
Hello @cianwilson. I've had  such problem. Issue #12  is all about problems with installation. You sould use [this advice.](https://github.com/drufat/triangle/issues/12#issuecomment-225918750) from @sinback (thank you, @sinback, again and again). It helped me, I think it will help you.

**Comment by cianwilson** [comment]
Many thanks @drufat, that fixed my problem (in a much neater way).

**Comment by cianwilson** [comment]
Also, thanks to @LonelyDeer.

**Comment by jesse2013** [comment]
I met the same problem  when I was installing rfoo.
