### ISSUE TITLE
Help with "loads" function

### ISSUE THREAD

**Issue by rogue26** [drufat/triangle#19]
Hi @drufat. You've really done a great job with this. Super easy to use. On a previous issue, you said that "At the moment triangle only supports loading, and not writing data."

Does that basically mean that the "loads" function isn't working right now? I'm trying to get a list of the neighboring cells for each cell and it looks like the .neigh file would have what I need. Is there a way to get that information without running  Jonathan Shewchuk’s code directly? Thanks.

**Comment by drufat** [comment]
Hi, I am glad you find triangle useful.  triangle is mainly focused around the triangulate function. It takes in python data types, and returns python data types. The loading of files is quite rudimentary at the moment. If you have to load and write files in the format used by the C library, that would probably be a better choice, although I am definitely open to accepting patches if you want to implement that functionality in triangle.
