### ISSUE TITLE
 error: Microsoft Visual C++ 14.0 is required

### ISSUE THREAD

**Issue by torecki** [drufat/triangle#28]
I am not able to build and install the package because of the error message:  

> building 'triangle.core' extension
> error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

I don't know how to fix. I installed the old version 14 but it doesn't work. 

Thanks for every tip in advance.

Torsten

**Comment by drufat** [comment]
I do not have much experience with Windows build tools ,but if you are able to fix the issue, I am open to accepting pull requests.

**Comment by drufat** [comment]
I have been able to install `triangle` on Windows 10 after downloading Microsoft Visual Studio. I am closing this bug report.
