### ISSUE TITLE
Running python setup.py install stopped working after 52c486246f42cc90be941a504e8ff8c88b54e5ec

### ISSUE THREAD

**Issue by SimonsUnikaNamn** [drufat/triangle#29]
Running the command `python setup.py install` gives

```Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from Cython.Build import cythonize
ImportError: No module named Cython.Build
The command '/bin/sh -c python setup.py install' returned a non-zero code: 1
```

on the latest commit 52c486246f42cc90be941a504e8ff8c88b54e5ec, it works when going to 4b924a299bf80843de826c1d4be3a8529d307536

**Comment by drufat** [comment]
Cython is a build depdency. Installing it by, for example, running `pip install cython` should fix that.

**Comment by SimonsUnikaNamn** [comment]
Excellent, thank you
