### ISSUE TITLE
triangles no longer returned

### ISSUE THREAD

**Issue by mikedh** [drufat/triangle#30]
Hi, it looks like with the new release `triangles` are no longer returned:

Code that used to work (JSON of args [in gist](https://gist.github.com/mikedh/c893ac62de7bd9fb7b43d457e6c31e9d)):
```
with open('arg.json', 'w') as f:
    arg = json.load(f)
from triangle import triangulate
result = triangulate(arg, 'pq30')
return result['vertices'], result['triangles']
```
If you embed and check returned keys, they are now missing 'triangles`:
```
In [9]: result.keys()
Out[9]: dict_keys(['vertices', 'vertex_markers', 'holes'])
```

**Comment by drufat** [comment]
Thanks for the bug report. The latest commit should fix this issue.

**Comment by drufat** [comment]
I also released a new version with the fix. Upgrade with `pip install triangle --upgrade`.

**Comment by mikedh** [comment]
Awesome! Thanks for the quick fix, I verified it fixed the issue.
