### ISSUE TITLE
Theory-of-seismic-waves-II/02_Mesh_generation/4_Tri_mesh_delaunay_yigma_tepe.ipynb

### ISSUE THREAD

**Issue by brioglade** [drufat/triangle#37]
AttributeError                            Traceback (most recent call last)
<ipython-input-24-a8f5012f730c> in <module>()
      2 cndt = triangle.triangulate(A,'pD')
      3 ax = plt.subplot(111, aspect='equal')
----> 4 tplot.plot(ax,**cndt)

AttributeError: 'function' object has no attribute 'plot'

**Comment by drufat** [comment]
Since `tplot` is a function, the code should probably read:
     tplot(ax,**cndt)

The triangle plot function is located in `triangle.plot`.
