### ISSUE TITLE
Project as a whole doesn't appear to be able to be licensed as LGPL-3

### ISSUE THREAD

**Issue by kmosiejczuk** [drufat/triangle#54]
I was reviewing this project for someone else and noticed that the bundled triangle library license ( https://github.com/drufat/triangle/blob/master/c/README ) is a non-commercial license that isn't compatible with LGPLv3. You should probably (at minimum), change your license file to reflect that the library part isn't licensed as LGPLv3.

**Comment by drufat** [comment]
The LGPLv3 only applies to the wrapper code not to the original library which has its own license.

**Comment by kmosiejczuk** [comment]
That may be your intention, but your Github and PyPI both just say the whole thing is LGPLv3. At the very least, it is going to lead to confusion and some folks violating the library's license.
