### ISSUE TITLE
Wheels for Python 3.9 / 3.10 on PyPI

### ISSUE THREAD

**Issue by stefsmeets** [drufat/triangle#57]
Thanks for this great library! I'm trying to migrate my code to use Python 3.9, but wheels on pypi are available up to and including Python 3.8. 

Would it be possible to upload wheels for python 3.9 and 3.10?

**Comment by carlosal1015** [comment]
I built successfully the python bindings for 3.9, but now for [3.10 we have some warnings/errors](https://gist.github.com/carlosal1015/604ddea740002f821173604341e3dca8).

**Comment by Korijn** [comment]
So how about uploading those 3.9 wheels to pypi? :)

**Comment by stefsmeets** [comment]
For anyone who is interested, I made wheels available here:
https://github.com/stefsmeets/triangle/releases/tag/20200804

The current github action appears to be broken (vcpython27 has been deprecated), so I will make a PR so that hopefully the builds on pypi can also be updated.

**Comment by carlosal1015** [comment]
Only curious, the date 20200804 could point to `date -u +"%Y%m%d"`.

**Comment by robbievanleeuwen** [comment]
Hi @drufat, [*sectionproperties*](https://github.com/robbievanleeuwen/section-properties) v2 now utilises triangle and we would also love to get python 3.9 wheels uploaded as implemented in #58 🙌

**Comment by carlosal1015** [comment]
Unlike the triangle-20200424 tarball, triangle-20220202 /c is empty.

**Comment by stefsmeets** [comment]
Thanks @drufat, works like charm! 🚀
