### ISSUE TITLE
[Feature Request] Make a new release

### ISSUE THREAD

**Issue by Hofer-Julian** [drufat/triangle#69]
The latest release of this library fails with Python 3.11: https://github.com/conda-forge/py-triangle-feedstock/pull/3

@mwtoews PR https://github.com/drufat/triangle/pull/67 fixes that.

Could you please make a new release so we can update the conda feedstock?

Thank you!

**Comment by connorferster** [comment]
I second this request :)

**Comment by ShayHill** [comment]
Third

**Comment by cheginit** [comment]
[Pandamesh](https://github.com/Deltares/pandamesh) depends on this package, so it would be great if, it gets updated, so it can work with py3.11.

**Comment by drufat** [comment]
Latest version now has builds for cp311 and cp312.
